---
title: Overview of Machine Learning Algorithms
author: Richard Wanjohi, Ph.D
date: '2018-04-03'
slug: overview-of-machine-learning-algorithms
categories: []
tags:
  - Python
  - R
---
$\color{red}{\text{ Draft: Work in Progress.....  }}$ 

***
### Learning Styles:

* Supervised Learning
     + The values of target variable, in training set are known.
     
* Unsupervised Learning
     + data is not labeled and outcomes are unknown.
     + Seek to find hidden structure in unlabeled data 
     + Example: Clustering algorithms

* Semi-supervised Learning
     + Uses both labeled and unlabeled data to improve supervised learning.
     + Example: in Deep learning Generative models


### Problems:
* Classification problem: The target variable is qualitative (categorical/nominal)
     + Binary- Two possible outcomes only
          + e.g. Yes/No, 0/1
     + Multi-Class- More than 2 outcomes
          + e.g. Positive, Neutral or Negative  customer sentiment/feedback

* Regression problem: The target is quantitative (discrete or continuous) 
    + Can take any real number in real line
        + e.g. Stock prices, estimated revenue, interest rates, price of house, Number of accidents 

   
* Others:
    +  Clustering
    +  Dimension reduction

***

```{python, eval=FALSE}
import pandas as pd
#from sklearn.cross_validation import train_test_split, StratifiedKFold 
from sklearn.ensemble  import GradientBoostingClassifier as GBC, RandomForestClassifier
from sklearn.model_selection import GridSearchCV

```



#### 1. Linear Regression:

*********


#### 2. Logistic Regression

**********

#### 3. Other regression problems


#### 4. Classification and Regression Trees (Decision Tree)

**********

#### 5. Naive Bayes

**********


#### 6. Ensemble Models

* Random Forest

* Boosted Trees
     + Adaptive boosting
     + Gradient Boosting
        * Gradient boost
        * XGBoost
        * Catboost
    
## 7. Support Vector Machine (SVM)



## 8. K-nearest neigbour (KNN)
